"""Onboarding scenarios focused on first-time GM core actions."""

from __future__ import annotations

from app.onboarding.tour_models import TourPlacement, TourStep

from .campaign_creation_contract import (
    CREATE_SCENARIO_FOR_ARC,
    ENTER_ARC_NAME,
    ENTER_ARC_OBJECTIVE,
    ENTER_ARC_SUMMARY,
    ENTER_CAMPAIGN_LOGLINE,
    ENTER_CAMPAIGN_NAME,
    ENTER_CAMPAIGN_OBJECTIVE,
    FINALIZE_CAMPAIGN,
    GO_TO_ARCS,
    GO_TO_REVIEW,
    MANAGE_ARCS_OPTIONAL,
    OPEN_WIZARD,
)


def build_new_gm_mvp_steps() -> list[TourStep]:
    """Hands-on first-use path for creating a campaign, arc, scenario, NPC, and place."""
    return [
        TourStep(
            id="new_gm_mvp.enter_campaign_name",
            screen=ENTER_CAMPAIGN_NAME.screen,
            target_widget_key=ENTER_CAMPAIGN_NAME.widget_key,
            title="1. Name the Campaign",
            description=ENTER_CAMPAIGN_NAME.expected_user_action,
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.enter_campaign_logline",
            screen=ENTER_CAMPAIGN_LOGLINE.screen,
            target_widget_key=ENTER_CAMPAIGN_LOGLINE.widget_key,
            title="2. Add the Premise",
            description=ENTER_CAMPAIGN_LOGLINE.expected_user_action,
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_mvp.enter_campaign_objective",
            screen=ENTER_CAMPAIGN_OBJECTIVE.screen,
            target_widget_key=ENTER_CAMPAIGN_OBJECTIVE.widget_key,
            title="3. Define the Objective",
            description=ENTER_CAMPAIGN_OBJECTIVE.expected_user_action,
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_mvp.go_to_arcs",
            screen=GO_TO_ARCS.screen,
            target_widget_key=GO_TO_ARCS.widget_key,
            title="4. Continue to Arcs",
            description=GO_TO_ARCS.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_mvp.add_arc",
            screen=MANAGE_ARCS_OPTIONAL.screen,
            target_widget_key=MANAGE_ARCS_OPTIONAL.widget_key,
            title="5. Create One Arc",
            description=MANAGE_ARCS_OPTIONAL.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_mvp.enter_arc_name",
            screen=ENTER_ARC_NAME.screen,
            target_widget_key=ENTER_ARC_NAME.widget_key,
            title="6. Name the Arc",
            description=ENTER_ARC_NAME.expected_user_action,
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.enter_arc_summary",
            screen=ENTER_ARC_SUMMARY.screen,
            target_widget_key=ENTER_ARC_SUMMARY.widget_key,
            title="7. Summarize the Arc",
            description=ENTER_ARC_SUMMARY.expected_user_action,
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_mvp.enter_arc_objective",
            screen=ENTER_ARC_OBJECTIVE.screen,
            target_widget_key=ENTER_ARC_OBJECTIVE.widget_key,
            title="8. Give the Arc an Objective",
            description=ENTER_ARC_OBJECTIVE.expected_user_action,
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_mvp.create_scenario_for_arc",
            screen=CREATE_SCENARIO_FOR_ARC.screen,
            target_widget_key=CREATE_SCENARIO_FOR_ARC.widget_key,
            title="9. Create the First Scenario",
            description=CREATE_SCENARIO_FOR_ARC.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_mvp.scenario_title",
            screen="scenario_builder",
            target_widget_key="input_scenario_title",
            title="10. Name the Scenario",
            description="Enter a scenario title. It will be saved and linked back to the selected campaign arc.",
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.scenario_notes",
            screen="scenario_builder",
            target_widget_key="btn_scenario_notes",
            title="11. Add Scenario Summary and Secrets",
            description='Use "Edit Notes" to add a short summary and any GM-facing secrets before planning scenes.',
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_mvp.scenario_guided_mode",
            screen="scenario_builder",
            target_widget_key="scenario_planning_mode",
            title="12. Plan Scenes in Guided Mode",
            description='Keep "guided" selected for a simple opening, middle, and finale structure. Add NPCs and Places to scene entity fields when they exist.',
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.scenario_next_relations",
            screen="scenario_builder",
            target_widget_key="btn_scenario_next",
            title="13. Continue Through Scenario Review",
            description='Click "Next" through Character Relations, Entity Linking, and Review. Use these steps to connect NPCs, places, factions, clues, and maps.',
            placement=TourPlacement.TOP,
        ),
        TourStep(
            id="new_gm_mvp.scenario_finish",
            screen="scenario_builder",
            target_widget_key="btn_scenario_finish",
            title="14. Save the Scenario",
            description='On the Review step, click "Finish" to save the scenario and attach it to the selected arc.',
            placement=TourPlacement.TOP,
        ),
        TourStep(
            id="new_gm_mvp.go_to_review",
            screen=GO_TO_REVIEW.screen,
            target_widget_key=GO_TO_REVIEW.widget_key,
            title="15. Review the Campaign",
            description=GO_TO_REVIEW.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_mvp.save_campaign",
            screen=FINALIZE_CAMPAIGN.screen,
            target_widget_key=FINALIZE_CAMPAIGN.widget_key,
            title="16. Save the Campaign",
            description=FINALIZE_CAMPAIGN.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_mvp.open_npcs",
            screen="main_window",
            target_widget_key="btn_open_npcs",
            title="17. Open NPCs",
            description='Open "NPCs" from the Campaign Workshop sidebar, then use the Add button to create a recurring NPC for the campaign.',
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_mvp.add_npc",
            screen="entity_npcs",
            target_widget_key="btn_add_entity",
            title="18. Add an NPC",
            description='Click "Add" to open the NPC editor.',
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.npc_name",
            screen="editor_npcs",
            target_widget_key="input_name",
            title="19. Name the NPC",
            description="Enter the NPC name first. Saving requires a name.",
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.npc_portrait",
            screen="editor_npcs",
            target_widget_key="btn_portrait_add",
            title="20. Choose a Portrait",
            description='Use "Add" to pick portrait image files. "Image Library" and "Create Portrait" are also available when you want to search or generate art.',
            placement=TourPlacement.TOP,
        ),
        TourStep(
            id="new_gm_mvp.npc_save",
            screen="editor_npcs",
            target_widget_key="btn_save",
            title="21. Save the NPC",
            description='Click "Save" so the NPC can be linked from scenarios, scenes, and campaign views.',
            placement=TourPlacement.TOP,
        ),
        TourStep(
            id="new_gm_mvp.open_places",
            screen="main_window",
            target_widget_key="btn_open_places",
            title="22. Open Places",
            description='Open "Places" from the Campaign Workshop sidebar, then add the first important location.',
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_mvp.add_place",
            screen="entity_places",
            target_widget_key="btn_add_entity",
            title="23. Add a Place",
            description='Click "Add" to open the Place editor.',
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.place_name",
            screen="editor_places",
            target_widget_key="input_name",
            title="24. Name the Place",
            description="Enter a location name. Add a description, tags, and links that make it useful during play.",
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_mvp.place_visual",
            screen="editor_places",
            target_widget_key="btn_portrait_add",
            title="25. Add a Place Visual",
            description='Use "Add" when you have a map, landmark, or location image. This makes the place easier to recognize in GM views.',
            placement=TourPlacement.TOP,
        ),
        TourStep(
            id="new_gm_mvp.place_save",
            screen="editor_places",
            target_widget_key="btn_save",
            title="26. Save the Place",
            description='Click "Save" so the place can be attached to scenes and campaign material.',
            placement=TourPlacement.TOP,
        ),
    ]


def build_new_gm_advanced_steps() -> list[TourStep]:
    """Extended quickstart using only controls that exist in the wizard."""
    return [
        TourStep(
            id="new_gm_advanced.open_campaign_builder",
            screen=OPEN_WIZARD.screen,
            target_widget_key=OPEN_WIZARD.widget_key,
            title="Open Campaign Builder",
            description=OPEN_WIZARD.expected_user_action,
            placement=TourPlacement.RIGHT,
        ),
        TourStep(
            id="new_gm_advanced.enter_campaign_name",
            screen=ENTER_CAMPAIGN_NAME.screen,
            target_widget_key=ENTER_CAMPAIGN_NAME.widget_key,
            title="Step 1: Campaign Name",
            description=ENTER_CAMPAIGN_NAME.expected_user_action,
            placement=TourPlacement.BOTTOM,
        ),
        TourStep(
            id="new_gm_advanced.next_to_arcs",
            screen=GO_TO_ARCS.screen,
            target_widget_key=GO_TO_ARCS.widget_key,
            title="Go to step 2",
            description=GO_TO_ARCS.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_advanced.manage_arcs_optional",
            screen=MANAGE_ARCS_OPTIONAL.screen,
            target_widget_key=MANAGE_ARCS_OPTIONAL.widget_key,
            title="Step 2: Arcs (optional)",
            description=MANAGE_ARCS_OPTIONAL.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_advanced.next_to_review",
            screen=GO_TO_REVIEW.screen,
            target_widget_key=GO_TO_REVIEW.widget_key,
            title="Go to step 3",
            description=GO_TO_REVIEW.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
        TourStep(
            id="new_gm_advanced.save_campaign",
            screen=FINALIZE_CAMPAIGN.screen,
            target_widget_key=FINALIZE_CAMPAIGN.widget_key,
            title="Final action",
            description=FINALIZE_CAMPAIGN.expected_user_action,
            placement=TourPlacement.LEFT,
        ),
    ]
